apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .KlusterletName }}-registration-sa
  namespace: {{ .AgentNamespace }}
{{ if eq .AwsIamProvider "irsa" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .AwsIamWorkerRoleArn }}
{{ end }}
imagePullSecrets:
- name: open-cluster-management-image-pull-credentials
